spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.springframework.security.config: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.apache.catalina: ERROR
    org.apache.tomcat: ERROR