spring:
  datasource:
    url: jdbc:h2:file:./data/afertechdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: renzo.masiero.dev@gmail.com
    password: xgfkucmnsuxxbjxd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: local-dev-secret-12345678901234567890