CREATE TABLE public.clients (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    tax_id character varying(255) NOT NULL
);

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.cost_types (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.cost_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.employees (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    document_number character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    hire_date date NOT NULL,
    last_name character varying(255) NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    termination_date date
);

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.exchange_rate (
    id bigint NOT NULL,
    date date NOT NULL,
    usd_ars_rate numeric(15,2),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    deleted_at timestamp without time zone,
    deleted_by character varying(255)
);

ALTER TABLE public.exchange_rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.fixed_costs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    allocation_month character varying(7) NOT NULL,
    amount numeric(38,2) NOT NULL,
    description character varying(500),
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    payment_date date NOT NULL,
    cost_type_id bigint NOT NULL,
    employee_id bigint,
    currency_original character varying(10) NOT NULL,
    exchange_rate_used numeric(15,2),
    amount_usd numeric(15,2)
);

ALTER TABLE public.fixed_costs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    deferred_payment_days integer,
    description character varying(255),
    invoice_number character varying(255) NOT NULL,
    issue_date date NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    purchase_order_percentage integer,
    total_with_tax numeric(38,2) NOT NULL,
    total_without_tax numeric(38,2) NOT NULL,
    client_id bigint NOT NULL,
    payment_order_id bigint,
    project_id bigint NOT NULL,
    purchase_order_id bigint NOT NULL,
    currency_original character varying(10) DEFAULT 'USD' NOT NULL,
    exchange_rate_used numeric(15,2),
    total_without_tax_usd numeric(15,2),
    total_with_tax_usd numeric(15,2)
);

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.payment_orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    concept character varying(500),
    executed boolean NOT NULL,
    execution_date date,
    issue_date date NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    payment_order_number character varying(255) NOT NULL,
    total_with_tax numeric(38,2) NOT NULL,
    total_without_tax numeric(38,2) NOT NULL,
    withholdings numeric(38,2),
    client_id bigint NOT NULL,
    invoice_id bigint,
    project_id bigint NOT NULL,
    purchase_order_id bigint,
    currency_original character varying(10) DEFAULT 'ARS' NOT NULL,
    exchange_rate_used numeric(15,2),
    total_without_tax_usd numeric(15,2),
    total_with_tax_usd numeric(15,2)
);

ALTER TABLE public.payment_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.projects (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    description character varying(500),
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.purchase_orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    description character varying(500),
    issue_date date NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    purchase_order_number character varying(255) NOT NULL,
    total_with_tax numeric(38,2) NOT NULL,
    total_without_tax numeric(38,2) NOT NULL,
    client_id bigint NOT NULL,
    project_id bigint NOT NULL,
    currency_original character varying(10) DEFAULT 'ARS' NOT NULL,
    exchange_rate_used numeric(15,2),
    total_without_tax_usd numeric(15,2),
    total_with_tax_usd numeric(15,2)
);

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.reminder_recipients (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    loaded_at timestamp without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    deleted_at timestamp without time zone,
    deleted_by character varying(255)
);

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    loaded_at timestamp(6) without time zone NOT NULL,
    loaded_by character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    tax_id character varying(255) NOT NULL
);

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    active boolean NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
);