-- ==========================================
-- V9__add_monetary_model_to_variable_cost.sql
-- Add monetary model (USD base) to variable_costs
-- ==========================================

CREATE TABLE IF NOT EXISTS variable_cost_types (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL UNIQUE,

    loaded_at TIMESTAMP NOT NULL,
    loaded_by VARCHAR(255) NOT NULL,

    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS variable_costs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    variable_cost_type_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    project_id BIGINT,

    description VARCHAR(500),

    amount DECIMAL(15,2) NOT NULL,

    currency_original VARCHAR(10),
    exchange_rate_used DECIMAL(15,2),
    amount_usd DECIMAL(15,2),

    allocation_month VARCHAR(7) NOT NULL,

    payment_date DATE NOT NULL,

    loaded_at TIMESTAMP NOT NULL,
    loaded_by VARCHAR(255) NOT NULL,

    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255)
);

ALTER TABLE variable_costs
ADD COLUMN IF NOT EXISTS currency_original VARCHAR(10);

ALTER TABLE variable_costs
ADD COLUMN IF NOT EXISTS exchange_rate_used DECIMAL(15,2);

ALTER TABLE variable_costs
ADD COLUMN IF NOT EXISTS amount_usd DECIMAL(15,2);

UPDATE variable_costs
SET currency_original = 'ARS'
WHERE currency_original IS NULL;

ALTER TABLE variable_costs
ALTER COLUMN currency_original SET NOT NULL;